### ISSUE TITLE
Thank you for your work. Can you provide training weights and data for testing

### ISSUE THREAD

**Issue by puallee** [jwc-rad/pix2pix3D-CT#1]
Thank you for your work. Can you provide training weights and data for testing?

**Comment by jwc-rad** [comment]
Unfortunately, the IRB approval did not cover any kind of sharing outside our institution. For data for testing, there are some public datasets where you could get non-contrast CT data.

**Comment by puallee** [comment]
How about the training model, can you provide it for us to test？

**Comment by jwc-rad** [comment]
The model weight has been released: [https://github.com/jwc-rad/pix2pix3D-CT/releases/download/v1.0.0/v1.0.0.7z](url).
Please follow the inference.ipynb notebook for inference. But, you may get errors because it's been a while since I've checked this model and this project was based on Tensorflow 1.4 and Keras 2.1.5. I recommend modifying the source codes for your environment and running the training from scratch.

**Comment by puallee** [comment]
Thanks for your sharing ！  In cfg.Jason.  I still lack  "df_path": "dicom/YOURDATASET/select.ftr", and  "splitvar": "result/paper/split.pkl" . Can you give me an example，thank you very much！

**Comment by jwc-rad** [comment]
If you look at [inference.ipynb](https://github.com/jwc-rad/pix2pix3D-CT/blob/main/inference.ipynb), you can save your own "select.ftr" using your own test dataset.
And, "splitvar" is set to 1.0 for inference.
